name: AudioBandProfileRepoSummarize

on:
  # Run on every push on the master branch
  push:
    branches: [ master ]
    paths-ignore: ProfilesSummary.json

  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path:  ./.github/workflows/ProfileRepoSummarizeAction
    - name: Install dependencies
      working-directory: ./.github/workflows/ProfileRepoSummarizeAction
      run: npm ci
    - name: Run script
      working-directory: ./.github/workflows/ProfileRepoSummarizeAction
      run: npm run start
      env: # Pass GitHub Token to script
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: ProfilesSummary.json
        path: ./.github/workflows/ProfileRepoSummarizeAction/ProfilesSummary.json
    - name: Update ProfilesSummary.json in repository
      run: mv -f ./.github/workflows/ProfileRepoSummarizeAction/ProfilesSummary.json .
    - name: Update file in repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: (Auto Commit) Update 'ProfilesSummary.json'
