name: AudioBandProfileRepoSummarize

on:
  # Run on every push on the master branch
  push:
    branches: [ master ]

  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      working-directory: ./.github/actions/ProfileRepoSummarizeAction
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      working-directory: ./.github/actions/ProfileRepoSummarizeAction
      run: npm ci
    - name: Run script
      working-directory: ./.github/actions/ProfileRepoSummarizeAction
      run: npm run start
